# -*- coding: utf-8 -*-
"""Untitled81.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNSYfuRXXSIqiW-Trgm3C2oadD1ES-mg
"""

import pandas as pd

brasil_estados = pd.read_feather('BR03.feather')
brasil_estados = brasil_estados[
    [
        'uf',
        'codigo',
        'area',
        'populacao',
        'densidade',
        'matricula',
        'idh',
        'receitas',
        'despesas',
        'rendimento',
        'veiculos',
        'regiao_nome'        
    ]
]
brasil_estados

brasil_estados['sigla'] = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 
                           'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 
                           'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
]

brasil_estados

brasil_cidades = pd.read_excel('BRCidades.xlsx')
brasil_cidades

brasil_cidades.info()

brasil_cidades['estado'].unique()

estados_localizacao_media = brasil_cidades.groupby('estado')[['latitude', 'longitude']].mean().reset_index()
estados_localizacao_media

brasil_estados = brasil_estados.merge(
    estados_localizacao_media,
    left_on = 'sigla',
    right_on = 'estado',
    how = 'left'
)
brasil_estados

import folium

mapa = folium.Map(location=[-15.7601, -47.8800], zoom_start=5)
for index, row in brasil_estados.iterrows():
    folium.CircleMarker(
        location=[
            row['latitude'], 
            row['longitude']
        ],    
        radius=3,
        popup=row['uf'],
        color='blue',
        fill=True,
        fill_color='lightblue'
    ).add_to(mapa)
mapa

mapa = folium.Map(location=[-15.7601, -47.8800], zoom_start=5)
for index, row in brasil_estados.iterrows():
    folium.Marker(
        location=[
            row['latitude'], 
            row['longitude']
        ],    
        radius=10,
        popup=row['uf'],
        color='blue',
        fill=True,
        fill_color='lightblue'
    ).add_to(mapa)
mapa



import json

geo_data = json.load(open('brazil-states.geojson.txt'))

geo_data['features'][1]



mapa = folium.Map(location=[-15.7601, -47.8800], zoom_start=5, tiles='cartodbpositron')
# Criando a camada Choroplet
mapa = folium.Choropleth(
    geo_data = geo_data,
    name ='choropleth',
    data = brasil_estados,
    columns = ['sigla','area'],
    key_on = 'feature.properties.sigla',
    fill_color = 'Reds',
    fill_opacity = 1.0,
    line_opacity = 0.9,
    line_color = 'grey', 
    line_weight = 0.25,
    legend_name = 'Area dos Estados',
    highlight = True,
    reset = True 

).add_to(mapa)

mapa.geojson.add_child(
  folium.features.GeoJsonTooltip(
      fields = ['uf','sigla','area'],
      aliases = ['Estado:','sigla:', 'Área:'],
      labels = True,
      localize = True,
      sticky = False,
  )
)

mapa

import plotly.express as px

minimo = brasil_estados['populacao'].min()
maximo = brasil_estados['populacao'].max()

mapa_px = px.choropleth_mapbox(
    data_frame = brasil_estados, 
    geojson = geo_data, 
    locations='sigla', 
    featureidkey='properties.sigla',
    color='populacao',
    color_continuous_scale= 'reds',
    hover_name = 'sigla', 
    hover_data =['uf', 'populacao', 'regiao_nome'],    
    range_color=(minimo, maximo),
    mapbox_style='carto-positron',
    zoom=3.5, 
    center = {"lat": -15.76, "lon": -47.88},
    opacity=1,
    labels={'populacao':'População', 
            'sigla' : 'Sigla',
            'uf': 'Estado',
            'regiao_nome': 'Região'
    },
    width = 1200,
    height = 800,
    title = 'Taxa de Mortalidade por Covid-19, por municípios, 11/08/2022'
)

# Ajustando as margens
mapa_px.update_layout(margin={'r':0,'t':0,'l':0, 'b':0})

# Reduzindo a largura das bordas dos municípios
mapa_px.update_traces(marker_line_width=1)

# Exibindo o mapa
mapa_px.show()